### ISSUE TITLE
Listening on all interfaces.

### ISSUE THREAD

**Issue by thz** [openvnf/vnf-ipsec#10]
strongswan/charon binds to all interfaces/addresses per default.

Expectation: interface or listening address is configurable.
Perhaps a specified local-ip can be used as a sane default.

**Comment by hwinkel** [comment]
related to https://github.com/openvnf/vnf-bgp/issues/3

**Comment by grundrauschen** [comment]
This issue is closed via 772cba1b0a4bf72ec36380e4868182ccbbea4949 and available in version 1.3.0

See [Documentation](https://github.com/openvnf/vnf-ipsec#configuration) with environmental variable `IPSEC_INTERFACES`.
